on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.dot"

jobs:
  dot:
    name: Render .dot files as .svg
    runs-on: ubuntu-latest
    steps:
#       - name: Setup Graphviz
#         uses: ts-graphviz/setup-graphviz@v1
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: List .dot files
        id: list-files
        run: echo "DOT_FILES=$(find . -name '*.dot' -print)" >> "$GITHUB_OUTPUT"
      - name: Debug
        run: echo "${{ steps.list-files.outputs.DOT_FILES }}"
#       - name: Convert .dot files to .svg
      - name: Upload .svg as artifacts
        uses: actions/upload-artifact@v3
        with:
          path: "**.svg"
          retention-days: 1
