on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.dot"

jobs:
  dot:
    name: Render .dot files as .svg
    runs-on: ubuntu-latest
    steps:
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: List .dot files
        id: list-files
        run: echo "::set-output name=FILELIST::$(find . -name '*.dot' -print)"
      - name: Debug
        run: |
          IFS="," read -a dot_dot_files <<< ${{ steps.list-files.outputs.FILELIST }}
          for i in "${dot_dot_files[@]}"; do
            file_path=$(dirname "${i}")
            file_name=$(basename "${i}")
            cd file_path
            cat file_name
          done
#       - name: Convert .dot files to .svg
#       - name: Upload .svg as artifacts
#         uses: actions/upload-artifact@v3
#         with:
#           name: 
#           path: my_file.txt
#           retention-days: 1
